# Generated by Django 3.2.7 on 2021-09-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meaning',
            old_name='current_word',
            new_name='word_fk',
        ),
    ]
